/**
 * Live demo entry.
 *
 * A minimal standalone page that previews the editor the way the BookStack
 * integration uses it: a textarea holds a Markdown table, a button opens the
 * modal editor on that Markdown, and the edited result is written back into the
 * textarea. It uses the shared core editor directly (no BookStack CodeMirror
 * auto-init) and the BookStack stylesheet, so the modal looks production-real.
 */

import { editTable, createTable } from '../core/src/index.js';
import '../bookstack/src/styles/styles.css';

const byId = <T extends HTMLElement>(id: string): T => {
    const el = document.getElementById(id);
    if (!el) throw new Error(`Missing #${id}`);
    return el as T;
};

const textarea = byId<HTMLTextAreaElement>('md');
const editBtn = byId<HTMLButtonElement>('edit');
const newBtn = byId<HTMLButtonElement>('new');
const darkToggle = byId<HTMLInputElement>('dark');
const status = byId<HTMLElement>('status');

function flash(message: string) {
    status.textContent = message;
}

/** Opens the modal editor on the textarea's Markdown and writes the result back. */
async function openEditor() {
    try {
        const result = await editTable(textarea.value, { darkTheme: darkToggle.checked });
        if (result.saved && result.markdown !== null) {
            textarea.value = result.markdown;
            flash('Saved — the Markdown above was regenerated by the editor.');
        } else {
            flash('Edit cancelled.');
        }
    } catch (err) {
        // editMarkdown throws when the textarea isn't a valid Markdown table.
        const reason = err instanceof Error ? err.message : String(err);
        flash(`${reason}. Try “New table”, or fix the Markdown above.`);
    }
}

/** Opens the editor on a fresh 3×2 table. */
async function newTable() {
    const result = await createTable(3, 2, { darkTheme: darkToggle.checked });
    if (result.saved && result.markdown !== null) {
        textarea.value = result.markdown;
        flash('New table created.');
    } else {
        flash('Creation cancelled.');
    }
}

editBtn.addEventListener('click', openEditor);
newBtn.addEventListener('click', newTable);

// Default the dark-theme toggle to the OS preference.
darkToggle.checked = window.matchMedia?.('(prefers-color-scheme: dark)').matches ?? false;
